# Generated by Django 2.1.7 on 2019-11-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=200, null=True)),
                ('application_num', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_num', models.CharField(blank=True, max_length=200, null=True)),
                ('notice_num', models.CharField(blank=True, max_length=200, null=True)),
                ('vienna_code', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant', models.CharField(blank=True, max_length=45, null=True)),
                ('applicated_date', models.DateField(blank=True, null=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=45, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
    ]
