# Generated by Django 2.2.6 on 2019-11-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='images',
            table='Images',
        ),
    ]
