# Generated by Django 2.1.7 on 2019-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woon', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='media/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
