# Generated by Django 2.1.7 on 2019-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woon', '0005_auto_20191120_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
