# Generated by Django 2.2.6 on 2019-11-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imageurl', models.URLField()),
                ('applicationNumber', models.BigIntegerField()),
                ('PublicationNumber', models.BigIntegerField()),
                ('classificationCode', models.BigIntegerField()),
                ('viennaCode', models.BigIntegerField()),
                ('applicantName', models.CharField(max_length=50)),
                ('publicationNumber', models.BigIntegerField()),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
